pipeline {
    agent any 

    tools {
        maven 'maven-3.9.2'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/ 
                    // here we cd to ./maven instead of ./itd-gitrepo because this pipeline will look for /home/ubuntu/workspace/nameofpipeline and execute in it
                    mvn clean package
                    cd ./target/ 
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: 'my-tomcat-deploy', path: '', url: 'http://18.222.69.117:8080/')], 
                                     contextPath: '/itdefined-war-1.0.0', 
                                     war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }

}
