apiVersion: v1         ## This will create app.conf file of secretfile in container's /app/secretfile-volume directory
kind: Pod
metadata:
  name: my-secretfile-pod
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secretfilevolume
      mountPath: /app/secretfile-volume/
  volumes:
  - name: secretfilevolume
    secretMap:
        name: my-secretfile   ###name given inside metadata of secretfile.yml
