apiVersion: v1 
kind: Secret 
metadata:
    name: my-secret
data: 
    db_user: aGFyc2hh          
    db_pass: cGFzc3dvcmQ=

##to turn something into code== echo -n 'vijay' | base64
## to turn base64 code into normal== echo -n 'code' | base64 -d
