apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: local   ##i am using specified amount of memory from my cluster
  accessModes:
  - ReadWriteMany            ##accessmode tells how a volume can can be accessed, in this case this volume can be readand write from multiple nodes
  capacity:
    storage: 2Gi
  hostPath:
    path: '/home/ubuntu/'


##A PV of a particular storageclass can only be bound to PVCs requesting that class.
###A PV with no storageClassName has no class and can only be bound to PVCs that request no particular class
