apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-vol                     ##give same name as given in volumes
      mountPath: /app/pvc-volume
  volumes: 
  - name: pvc-vol
    persistentVolumeClaim:
        claimName: my-pvc     ##give same name as given for persistent volume claim to bind
