apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hostpath-vol                   ###should give the same name as given in the volumes to mount
      mountPath: /app/container-volume
  volumes: 
  - name: hostpath-vol                       #can give any name here
    hostPath: 
       path: /home/ubuntu/pod_data
       type: DirectoryOrCreate
