apiVersion: v1
kind: Pod
metadata:
  name: my-configfile-pod
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: configfilevolume
      mountPath: /app/configfile-volume
  volumes: 
  - name: configfilevolume
    configmap:
        name: 
