apiVersion: v1
kind: Pod
metadata:
    name: ip-app-cm
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT          ###value present in env goes toENVIRONMENT
      valueFrom:
          configMapKeyRef:
              name: my-cm    ###configmaps name
              key: env
    - name: APP
      valueFrom:
          configMapKeyRef:
              name: my-cm         ###configmaps name
              key: app   
