pipeline
{
    agent none
    stages{
        stage('directory')
        {
          agent any
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr vijay', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
        stage('list')
        {
          agent any
            steps
            {
            sh "ls -lrt"
            }
        }
    }
}

