apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
       app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
        - name: my-nginx
          image: harshajain/ip_app:latest
          ports:
           - containerPort: 8080
