apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-with-hpa         ## NAME given here will be mentioned in HPA again
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-application
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service 
metadata: 
    name: php-app-ci
spec:  
    selector:
        app: php-app      ### SELECTOR WE USE INSIDE SERVICES IS 100% LABEL OF PODS
    ports: 
      - port: 80
## We dont mention targetPort here as k8s finds it as we have selected a pod using label
        
