apiVersion: apps/v1
kind: Deployment
metadata:
  name: put-load-on-php
spec:
  replicas: 4
  selector:
    matchLabels:
      app: put-laod
  template:
    metadata:
      labels:
        app: put-laod
    spec:
      containers:
      - name: load-php
        image: busybox
        command: 
        - /bin/sh 
        - -c 
        - "while true; do wget -q http://php-app-ci; done"       
 ### WE use name of service to put load on deployment with one replica  create one more as cpu utilization crossed till cpu comes to desired
